version: '3'
services:
  web:
    image: <ACCOUNTID>.dkr.ecr.eu-central-1.amazonaws.com/flaskserver:v2
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: handson
        awslogs-region: eu-central-1
        awslogs-stream-prefix: web
